---
apiVersion: v1
kind: Service
metadata:
  name: secure-app
  namespace: secure-app-space
spec:
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app: secure-app
